### ISSUE TITLE
Alternative to this library

### ISSUE THREAD

**Issue by MartinMystikJonas** [Kdyby/PayPalExpress#9]
Just for your info: We crated new library inspired by this libary to work with PayPal but which uses official PayPal PHP SDK.

See https://github.com/MetisFW/PayPal

**Comment by fprochazka** [comment]
Is it okey, if I mark this lib as abandoned on packagist and direct the users to you?

**Comment by MartinMystikJonas** [comment]
@fprochazka It will be our honor! :-)

**Comment by fprochazka** [comment]
Done https://github.com/Kdyby/PayPalExpress/commit/e75741ec47d45bfeecf5280d90e3e5614413cb5c :)
